### ISSUE TITLE
Can you share your dataset?

### ISSUE THREAD

**Issue by NonvolatileMemory** [LynetteXing1991/TA-Seq2Seq#1]
hello Chen,your work is really excitied!
But can you share your dataset?

**Comment by weizier** [comment]
+1

**Comment by mengyanggithub** [comment]
+1

**Comment by Powerhui** [comment]
Hello,I am a student of China ,could you please share your dataset?

**Comment by Kiteflyingee** [comment]
+1

**Comment by crystalmoore** [comment]
hello, Chen. Would you like to share your dataset？
